name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
      with:
        swift-verion: '5.6.1'
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
